/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.GovtAdminRole;

/**
 *
 * @author shriyadikshith
 */
public class Govtadmin extends javax.swing.JPanel {

    /**
     * Creates new form Govtadmin
     */
    public Govtadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(130, 163, 165));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME SYSTEM ADMIN");
        add(jLabel1);
        jLabel1.setBounds(250, 20, 360, 32);

        jButton1.setText("Manage approvals");
        add(jButton1);
        jButton1.setBounds(40, 500, 210, 60);

        jButton2.setText("VIeiw Patient Records");
        add(jButton2);
        jButton2.setBounds(630, 510, 200, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/GovtAdminRole/govtadmin.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-10, 0, 860, 820);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
