/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.AppAdminArea;

import DisasterMgmtSystem.AppUserAccount.AppUserAccount;
import DisasterMgmtSystem.DisasterMgmtSystem;
import DisasterMgmtSystem.Enterprise.Enterprise;
import DisasterMgmtSystem.Organizations.Organization;
import javax.lang.model.SourceVersion;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author hs_sa
 */
public class AppAdminWorkArea extends javax.swing.JPanel {
    int tabIndex;
    JPanel userProcessContainer;
    AppUserAccount userAccount;
    DisasterMgmtSystem system;
    Organization org;
    Enterprise ep;
    /**
     * Creates new form SystemAdminWorkArea
     */
    public AppAdminWorkArea(JPanel userProcessContainer, AppUserAccount userAccount, DisasterMgmtSystem system, Organization org, Enterprise ep) {
        initComponents();
        this.tabIndex =0;
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        InitializeInterface();
    }
    
    private void InitializeInterface() {
        //Initializes the Tabbed UI with the below tabs;
        ManageDisasterNetwork createRest = new ManageDisasterNetwork(this.userProcessContainer, this.system);
        jTabbedPane1.addTab("Manage Networks", createRest);
        jTabbedPane1.addTab("Manage Enterprise", null);
        jTabbedPane1.addTab("Manage Enterprise Admin", null);

    }

    /**
     * Creates new form AppAdminWorkArea
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        selectedNodeJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(37, 116, 187));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 394));

        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        jPanel1.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 220, 140));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1130, 860));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Selected Node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        selectedNodeJLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        selectedNodeJLabel.setText("<view_selected_node>");
        jPanel2.add(selectedNodeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setText("System Admin Work Area");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, 50));

        jSplitPane1.setRightComponent(jPanel2);

        jPanel.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(479, 479, 479))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            selectedNodeJLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_JTreeValueChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if(this.tabIndex == jTabbedPane1.getSelectedIndex()){
            return;
        }
        else{
            this.tabIndex = jTabbedPane1.getSelectedIndex();
            if(jTabbedPane1.getSelectedIndex() == 0){
                ManageDisasterNetwork mnp = new ManageDisasterNetwork(this.userProcessContainer, this.system);
                jTabbedPane1.setComponentAt(jTabbedPane1.getSelectedIndex(), mnp);
            }
            else if(jTabbedPane1.getSelectedIndex() == 1){
                ManageEnterpriseNetwork mep = new ManageEnterpriseNetwork(this.userProcessContainer, this.system);
                jTabbedPane1.setComponentAt(jTabbedPane1.getSelectedIndex(), mep);
            }
            else if(jTabbedPane1.getSelectedIndex() == 2){
                ManageEnterpriseAdminPanel meap = new ManageEnterpriseAdminPanel(this.userProcessContainer, this.system);
                jTabbedPane1.setComponentAt(jTabbedPane1.getSelectedIndex(),meap);
            }

        }
    }//GEN-LAST:event_jTabbedPane1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables

    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }
}
