/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.sosReporter;

import DisasterMgmtSystem.DisasterMgmtSystem;
import DisasterMgmtSystem.Emergencies.Emergency;
import DisasterMgmtSystem.EmergencyLocation.EmergencyLocation;
import javax.swing.JPanel;

/**
 *
 * @author shriyadikshith
 */
public class sosReporterPanel extends javax.swing.JPanel {

    /**
     * Creates new form sosReporterPanel
     */
    private JPanel workArea;
    DisasterMgmtSystem disasterMgmtSystem;
    public sosReporterPanel(JPanel workArea) {
        initComponents();
        populateEmergencyType();
        
        this.workArea = workArea;
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prioritySlider = new javax.swing.JSlider();
        txtPhone = new javax.swing.JTextField();
        comboEmergency = new javax.swing.JComboBox<>();
        btnReport = new javax.swing.JButton();
        comboLocation = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("LOCATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 93, 128, 43));

        jLabel2.setText("PHONE NUMBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 175, 133, 43));

        jLabel3.setText("PRIORITY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 264, -1, -1));

        jLabel4.setText("EMERGENCY TYPE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, -1, -1));

        prioritySlider.setMajorTickSpacing(1);
        prioritySlider.setMaximum(10);
        prioritySlider.setMinimum(1);
        prioritySlider.setMinorTickSpacing(1);
        prioritySlider.setPaintLabels(true);
        prioritySlider.setPaintTicks(true);
        prioritySlider.setToolTipText("");
        prioritySlider.setValue(1);
        jPanel1.add(prioritySlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 244, -1, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 185, 110, -1));

        comboEmergency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Storm", "Earthquake", "Flood", "Forest Fire" }));
        comboEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmergencyActionPerformed(evt);
            }
        });
        jPanel1.add(comboEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 34, -1, -1));

        btnReport.setText("REPORT");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 361, -1, -1));

        comboLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLocationActionPerformed(evt);
            }
        });
        jPanel1.add(comboLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 103, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMERGENCY CONTROL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void comboEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEmergencyActionPerformed

    private void comboLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox<String> comboEmergency;
    private javax.swing.JComboBox<String> comboLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider prioritySlider;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void populateEmergencyType() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         for (Emergency.EmergencyType type : Emergency.EmergencyType.values()) 
         {
            String value = type.getValue();
            comboEmergency.addItem(value);
        }
    }
    
    private void populateLocation() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         comboLocation.removeAllItems();
         for (EmergencyLocation area : disasterMgmtSystem.getEmergencyLocationDirectory().getEmergencyLocationList()) 
         {
            comboLocation.addItem(area.getAddress());
        }
    }
    
    
}
