/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.sosReporter;

import DisasterMgmtSystem.Network.Network;
import DisasterMgmtSystem.AppUserAccount.AppUserAccount;
import DisasterMgmtSystem.DisasterMgmtSystem;
import DisasterMgmtSystem.Emergencies.DisasterEmergency;
import DisasterMgmtSystem.Emergencies.Emergency;
import DisasterMgmtSystem.Emergencies.EmergencyDirectory;
import DisasterMgmtSystem.EmergencyLocation.EmergencyLocation;
import DisasterMgmtSystem.Enterprise.Enterprise;
import DisasterMgmtSystem.Enterprise.PoliceAdministrator;
import DisasterMgmtSystem.SOSWaitList.PoliceWaitList;
import UserInterface.SOSPanel;
import Utilities.AlertMessage;
import Utilities.MainJFrameUtilities;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shriyadikshith
 */
public class sosReporterPanel extends javax.swing.JPanel {

    /**
     * Creates new form sosReporterPanel
     */
    private JPanel workArea;
    DisasterMgmtSystem disasterMgmtSystem;
    DisasterMgmtSystem system;
    private EmergencyDirectory emergencyDirectory;
    AppUserAccount userAccount;
    
    
    public sosReporterPanel(JPanel workArea, DisasterMgmtSystem disasterSystem) {
        initComponents();
        this.system = disasterSystem;
        this.workArea = workArea;
        this.emergencyDirectory = system.getEmergencyDirectory();
        this.disasterMgmtSystem = disasterSystem;
        this.userAccount = system.getUserAccountDirectory().authenticateUser("reporter", "reporter");
        populateDescriptionComboBox();
        populateLocation();
        this.workArea = workArea;
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prioritySlider = new javax.swing.JSlider();
        txtPhone = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        locationEmergencyTF = new javax.swing.JComboBox<>();
        phoneErr = new javax.swing.JLabel();
        descriptionCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("LOCATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 93, 128, 43));

        jLabel2.setText("PHONE NUMBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 133, 43));

        jLabel3.setText("PRIORITY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel4.setText("EMERGENCY TYPE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, -1, -1));

        prioritySlider.setMajorTickSpacing(1);
        prioritySlider.setMaximum(10);
        prioritySlider.setMinimum(1);
        prioritySlider.setMinorTickSpacing(1);
        prioritySlider.setPaintLabels(true);
        prioritySlider.setPaintTicks(true);
        prioritySlider.setToolTipText("");
        prioritySlider.setValue(1);
        jPanel1.add(prioritySlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 110, -1));

        btnReport.setText("REPORT");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        locationEmergencyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationEmergencyTFActionPerformed(evt);
            }
        });
        jPanel1.add(locationEmergencyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 103, 90, -1));
        jPanel1.add(phoneErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 80, 20));

        descriptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionComboActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 168, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMERGENCY CONTROL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        Emergency emergency;
        String location;
        
        if (txtPhone.getText().matches("[0-9]+") && (txtPhone.getText().length() == 10)) {
            phoneErr.setText("");
            
            emergency = this.emergencyDirectory.createNaturalEmergency();
            emergency.setLocationOfEmergency(locationEmergencyTF.getSelectedItem() + "");
            emergency.setCallersPhoneNumber(txtPhone.getText());
            emergency.setNatureOfEmergency((String) descriptionCombo.getSelectedItem());
            emergency.setDescription((String) descriptionCombo.getSelectedItem());
            emergency.setPriority(prioritySlider.getValue());
            emergency.setEmergencyStatus("Reported");
            
            Date d = new Date();
            emergency.setReportedTime(d);
            btnReport.setEnabled(false);
            txtPhone.setEditable(false);
            location = emergency.getLocationOfEmergency().replaceAll("\\s", "+");
            
            for (Network n : system.getNetworkList()) {
                for (Enterprise ent : n.getEntDirObj().getEnterpriseList()) {
                    if (ent instanceof PoliceAdministrator) {
                        for (AppUserAccount userAcc : ent.getUserAccountDirectory().getUserAccountList()) {

                            PoliceWaitList request = new PoliceWaitList();
                            request.setEmployee(ent.getEmployeeDirectory().getEmployeeList().get(0));
                            request.setEmergency(emergency);
                            emergency.setEmergencyStatus("Assigned to PSAP");
                            request.setReceiver(userAcc);
                            request.setSender(userAccount);
                            userAcc.getWorkQueue().getWorkRequestList().add(request);
                            request.setEmployee(userAccount.getEmployee());
                            request.setEmergency(emergency);
                            request.setReceiver(userAccount);
                            request.setSender(userAccount);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                        }
                    }
                }
            }
            
            //AlertMessage.sendTextMessage(jComboBox1.getSelectedItem() + callersPhoneNumberTF.getText(), "The emergency has been reported, Police are alerted and an ambulance will reach out soon!");
            JOptionPane.showMessageDialog(this, "The emergency has been reported, Police are alerted and an ambulance will reach out soon!");

            MainJFrameUtilities.redirect(new SOSPanel(this.workArea, this.system), "SOSPanel");
            
            }
        
        
        
        
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void locationEmergencyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationEmergencyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationEmergencyTFActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void descriptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox descriptionCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> locationEmergencyTF;
    private javax.swing.JLabel phoneErr;
    private javax.swing.JSlider prioritySlider;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void populateEmergencyType() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         for (Emergency.EmergencyType type : Emergency.EmergencyType.values()) 
         {
            String value = type.getValue();
            descriptionCombo.addItem(value);
        }
    }
    
    public void populateDescriptionComboBox() {
        descriptionCombo.removeAllItems();
       // if (emrg.equalsIgnoreCase("Disaster Emergency")) {
            DisasterEmergency accEmerg = new DisasterEmergency();
            for (String d : accEmerg.getDisasterList()) {
                descriptionCombo.addItem(d);
            }
        //}
    }
    
    private void populateLocation() {
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         locationEmergencyTF.removeAllItems();
         for (EmergencyLocation area : disasterMgmtSystem.getDirectory().getEmergencyLocationList()) 
         {
            locationEmergencyTF.addItem(area.getAddress());
        }
    }
    
    
}
