/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ReceptionRole;

import EcoSystem.EcoSystem;
import EcoSystem.Pharmacy.Pharmacy;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hs_sa
 */
public class ManageReceptionInformation extends javax.swing.JPanel {

    /**
     * Creates new form ManageReceptionInformation
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    Pharmacy restaurant;

    public ManageReceptionInformation(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        restaurant = (Pharmacy)userAccount;
        initComponents();
        display(restaurant);
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPageHeader = new javax.swing.JLabel();
        lblReceptionistName = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtReceptionistName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(166, 203, 230));
        setLayout(new java.awt.GridBagLayout());

        lblPageHeader.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        lblPageHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblPageHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPageHeader.setText("MANAGE RECEPTION INFORMATION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 254;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 0, 0, 0);
        add(lblPageHeader, gridBagConstraints);

        lblReceptionistName.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblReceptionistName.setForeground(new java.awt.Color(255, 255, 255));
        lblReceptionistName.setText("Receptionist Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 163, 0, 0);
        add(lblReceptionistName, gridBagConstraints);

        btnUpdate.setBackground(new java.awt.Color(97, 147, 160));
        btnUpdate.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 209, 0, 0);
        add(btnUpdate, gridBagConstraints);

        txtReceptionistName.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txtReceptionistName.setForeground(new java.awt.Color(255, 153, 51));
        txtReceptionistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceptionistNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 4, 0, 0);
        add(txtReceptionistName, gridBagConstraints);

        btnSave.setBackground(new java.awt.Color(97, 147, 160));
        btnSave.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 32, 0, 0);
        add(btnSave, gridBagConstraints);

        btnBack.setBackground(new java.awt.Color(97, 147, 160));
        btnBack.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        add(btnBack, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 668;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 0, 11, 0);
        add(jLabel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void setVisibleEditable(boolean value) {
        txtReceptionistName.setEditable(value);        
        txtReceptionistName.setEnabled(value);       
    }

    private void display(Pharmacy restaurant) {
        setVisibleEditable(false);
        txtReceptionistName.setText(restaurant.getPharmacyName());        
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       btnSave.setVisible(true);
       setVisibleEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtReceptionistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceptionistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceptionistNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        restaurant.setPharmacyName(txtReceptionistName.getText());
        setVisibleEditable(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ReceptionWorkArea adminWorkAreaJPanel = new ReceptionWorkArea(userProcessContainer,userAccount, ecosystem);
        userProcessContainer.add("AdminWorkAreaJPanel", adminWorkAreaJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPageHeader;
    private javax.swing.JLabel lblReceptionistName;
    private javax.swing.JTextField txtReceptionistName;
    // End of variables declaration//GEN-END:variables
}
