/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Police;

import DisasterMgmtSystem.AppUserAccount.AppUserAccount;
import DisasterMgmtSystem.DisasterMgmtSystem;
import DisasterMgmtSystem.Emergencies.Emergency;
import DisasterMgmtSystem.Enterprise.Enterprise;
import DisasterMgmtSystem.Network.Network;
import DisasterMgmtSystem.Victim.Victim;
import Utilities.AlertMessage;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hs_sa
 */
public class RetrieveVictimInformationPopUp extends javax.swing.JPanel {

    /**
     * Creates new form RetrieveVictimInformationPopUp
     */
    
    JPanel userProcessContainer;
    AppUserAccount account;
    DisasterMgmtSystem system;
    Network network;
    Enterprise enterprise;
    private boolean manageFields=false;
    Emergency emergency;
    public RetrieveVictimInformationPopUp(JPanel userProcessContainer, AppUserAccount account, DisasterMgmtSystem system, Network network, Enterprise enterprise, Emergency emergency) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.system=system;
        this.network=network;
        this.enterprise=enterprise;
        manageFields(manageFields);
        alertFamBtn.setVisible(false);
        this.emergency = emergency;
    }
    
    public void manageFields(boolean display)
    {
        nameLabel.setVisible(display);
        nameTF.setVisible(display);
        ageLabel.setVisible(display);
        ageTF.setVisible(display);
        addressLabel.setVisible(display);
        addressTF.setVisible(display);
        licensePlaeNumberLabel.setVisible(display);
        licensePlateTF.setVisible(display);
        phoneNumberLabel.setVisible(display);
        phoneNumberTF.setVisible(display);
        emergencyContactNumberLabel.setVisible(display);
        emergencyContactNumberTF.setVisible(display);
        nameTF.setEditable(false);
        ageTF.setEditable(false);
        addressTF.setEditable(false);
        licensePlateTF.setEditable(false);
        phoneNumberTF.setEditable(false);
        emergencyContactNumberTF.setEditable(false);

    }

    public long getDifference(long time1, long time2){
        return (time1 - time2)/1000%60;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        licensePlateLabel = new javax.swing.JLabel();
        licensePlateNumberTF = new javax.swing.JTextField();
        retrieveDataBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        licensePlaeNumberLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        licensePlateTF = new javax.swing.JTextField();
        phoneNumberTF = new javax.swing.JTextField();
        emergencyContactNumberTF = new javax.swing.JTextField();
        emergencyContactNumberLabel = new javax.swing.JLabel();
        alertFamBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Police admin work area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        licensePlateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        licensePlateLabel.setText("Retrieve person data from license plate:");
        jPanel2.add(licensePlateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        licensePlateNumberTF.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.add(licensePlateNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 138, 25));

        retrieveDataBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        retrieveDataBtn.setText("Retrieve data");
        retrieveDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveDataBtnActionPerformed(evt);
            }
        });
        jPanel2.add(retrieveDataBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nameLabel.setText("Name:");
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        ageLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ageLabel.setText("Age:");
        jPanel2.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        addressLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addressLabel.setText("Address:");
        jPanel2.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        licensePlaeNumberLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        licensePlaeNumberLabel.setText("License plate number:");
        jPanel2.add(licensePlaeNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        phoneNumberLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Phone number:");
        jPanel2.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));
        jPanel2.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 145, -1));
        jPanel2.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 145, -1));

        addressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTFActionPerformed(evt);
            }
        });
        jPanel2.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 145, -1));
        jPanel2.add(licensePlateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 145, -1));
        jPanel2.add(phoneNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 145, -1));
        jPanel2.add(emergencyContactNumberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 145, -1));

        emergencyContactNumberLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        emergencyContactNumberLabel.setText("Emergency contact number:");
        jPanel2.add(emergencyContactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        alertFamBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        alertFamBtn.setText("Alert Emergency Contact");
        alertFamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertFamBtnActionPerformed(evt);
            }
        });
        jPanel2.add(alertFamBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 661, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void retrieveDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveDataBtnActionPerformed
        // TODO add your handling code here:

        //String licensePlateNumber=licensePlateNumberTF.getText();
        boolean found=false;
        for(Victim p:system.getPersonDirectory().getPersonList())
        {
            //if(p.getLicensePlateNumber().equalsIgnoreCase(licensePlateNumber))
            {
                found=true;
                this.emergency.setPerson(p);
                this.emergency.setEmergencyContact(p.getEmergencyContactNumber());
                manageFields(true);
                nameTF.setText(p.getName());
                ageTF.setText(Integer.toString(p.getAge()));
                addressTF.setText(p.getAddress());
               // licensePlateTF.setText(p.getLicensePlateNumber());
                phoneNumberTF.setText(p.getPhoneNumber());
                emergencyContactNumberTF.setText(p.getEmergencyContactNumber());
                alertFamBtn.setVisible(true);
            }

        }
//        if(found == false)
//        {
//            JOptionPane.showMessageDialog(this, "This car has not been registered, cannot locate in database!");
//        }
    }//GEN-LAST:event_retrieveDataBtnActionPerformed

    private void addressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTFActionPerformed

    private void alertFamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertFamBtnActionPerformed
        // TODO add your handling code here:
        this.emergency.setEmergencyStatus("Family alerted");
        Date d = new Date();
        this.emergency.setAlertedThePatientEmergencyContact(d);
        this.emergency.setTotatTimeTakenByPoliceToAlertEmergencyContact(getDifference(this.emergency.getAlertedThePatientEmergencyContact().getTime(), this.emergency.getPoliceAlerted().getTime()));
        AlertMessage.sendTextMessage(this.emergency.getEmergencyContact(), "Don't Panic. You are getting this text because, your family member - " + this.emergency.getPerson().getName() + " has met with an accident. Contact us for more information");
        JOptionPane.showMessageDialog(this,"Text message sent to the Family member " + this.emergency.getEmergencyContact());
    }//GEN-LAST:event_alertFamBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton alertFamBtn;
    private javax.swing.JLabel emergencyContactNumberLabel;
    private javax.swing.JTextField emergencyContactNumberTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel licensePlaeNumberLabel;
    private javax.swing.JLabel licensePlateLabel;
    private javax.swing.JTextField licensePlateNumberTF;
    private javax.swing.JTextField licensePlateTF;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTF;
    private javax.swing.JButton retrieveDataBtn;
    // End of variables declaration//GEN-END:variables
}
