/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HospitalAdmin;

import EcoSystem.AmbulanceDriver.AmbulanceDriver;
import EcoSystem.AmbulanceDriver.AmbulanceDriverDirectory;
import EcoSystem.EcoSystem;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkList.LabWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shriyadikshith
 */
public class AcceptEmergencyRequest extends javax.swing.JPanel {

    /**
     * Creates new form Accept
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem ecosystem;
    LabWorkRequest labTestWorkRequest;
    double total = 0.0;
    
    private AmbulanceDriverDirectory ambulanceDriverDirectory;
    private int index = -1;
    
    public AcceptEmergencyRequest(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount, LabWorkRequest labTestWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        this.labTestWorkRequest = labTestWorkRequest;
        
        ambulanceDriverDirectory = ecosystem.getAmbulanceDirectory();   
        fillDelList(ambulanceDriverDirectory.getAmbulanceDriverList());
        change();
        
        display();
    }
    
    private void fillDelUI() {
        if(labTestWorkRequest.getAmbulanceDriver()== null && !("Request to HospitalAdmin".equalsIgnoreCase(labTestWorkRequest.getStatus()) || "declined".equalsIgnoreCase(labTestWorkRequest.getStatus()))){
            assignDeliveryPersonLabel.setVisible(true);
            assignDeliveryPerson.setVisible(true);
            
            btnassign.setVisible(true);
            
        }
        else{
            btnassign.setVisible(false);
            assignDeliveryPersonLabel.setVisible(false);
            assignDeliveryPerson.setVisible(false);
        }
    }
    
    private void display() {
        
        fillDelUI();
        
        
        status.setText(labTestWorkRequest.getStatus());
        message.setText(labTestWorkRequest.getMessage());

    }
    
    public void fillDelList(ArrayList<AmbulanceDriver> ambulanceDriverList) {
        if(labTestWorkRequest.getAmbulanceDriver()== null) {
            assignDeliveryPerson.setVisible(true);
            for (AmbulanceDriver ambulanceDriver : ambulanceDriverList) {
                assignDeliveryPerson.addItem(ambulanceDriver.getAmbulanceDriverName());
            }
        }
        else {
            assignDeliveryPerson.setVisible(false);
        } 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        assignDeliveryPersonLabel = new javax.swing.JLabel();
        assignDeliveryPerson = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        btnaccept = new javax.swing.JButton();
        btndecline = new javax.swing.JButton();
        btnassign = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 203, 230));
        setLayout(null);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(49, 61, 147, 53);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HospitalAdmin/emergencyimg.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(40, 240, 970, 710);

        jLabel12.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("EMERGENCY REQUEST DETAILS");
        add(jLabel12);
        jLabel12.setBounds(270, 30, 583, 43);

        assignDeliveryPersonLabel.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        assignDeliveryPersonLabel.setText("Assign Ambulance Driver");
        add(assignDeliveryPersonLabel);
        assignDeliveryPersonLabel.setBounds(260, 140, 237, 22);

        assignDeliveryPerson.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        assignDeliveryPerson.setForeground(new java.awt.Color(255, 153, 51));
        assignDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDeliveryPersonActionPerformed(evt);
            }
        });
        add(assignDeliveryPerson);
        assignDeliveryPerson.setBounds(570, 140, 150, 27);

        jLabel14.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel14.setText("Status");
        add(jLabel14);
        jLabel14.setBounds(440, 170, 57, 22);

        status.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("<value>");
        add(status);
        status.setBounds(590, 170, 79, 22);

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel10.setText("Message");
        add(jLabel10);
        jLabel10.setBounds(420, 200, 81, 22);

        message.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setText("<value>");
        add(message);
        message.setBounds(590, 200, 79, 22);

        btnaccept.setText("ACCEPT");
        btnaccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacceptActionPerformed(evt);
            }
        });
        add(btnaccept);
        btnaccept.setBounds(760, 200, 97, 29);

        btndecline.setText("DECLINE");
        add(btndecline);
        btndecline.setBounds(890, 200, 98, 29);

        btnassign.setText("ASSIGN");
        add(btnassign);
        btnassign.setBounds(760, 140, 97, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void assignDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDeliveryPersonActionPerformed
        index = assignDeliveryPerson.getSelectedIndex();
    }//GEN-LAST:event_assignDeliveryPersonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ViewEmergencyRequestPanel viewEmergencyRequestJPanel = new ViewEmergencyRequestPanel(userProcessContainer,ecosystem, userAccount);
        userProcessContainer.add("ViewEmergencyRequestJPanel", viewEmergencyRequestJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnacceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacceptActionPerformed
        // TODO add your handling code here:
         if (labTestWorkRequest.getStatus().equals("Request to HospitalAdmin")) {
            labTestWorkRequest.setStatus("Ambulance on the way"); 
            JOptionPane.showMessageDialog(null, " Request Accepted");
        }
        else if(labTestWorkRequest.getStatus().equals("Ambulance on the way")) {
            labTestWorkRequest.setStatus("Request to AmbulanceDriver");
            if(labTestWorkRequest.getDeliverMan() == null){
                JOptionPane.showMessageDialog(null, " Requested Ambulance");
            }
            else {
                JOptionPane.showMessageDialog(null, "Ambulance will be arriving");
            }
        }
        else {  
            btnaccept.setVisible(false);
        }
        change();
        status.setText(labTestWorkRequest.getStatus());
    }//GEN-LAST:event_btnacceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> assignDeliveryPerson;
    private javax.swing.JLabel assignDeliveryPersonLabel;
    private javax.swing.JButton btnaccept;
    private javax.swing.JButton btnassign;
    private javax.swing.JButton btndecline;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel message;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

private void change() {
        switch(labTestWorkRequest.getStatus()){
            case "Request to HospitalAdmin" -> {
                btnaccept.setText("Accept request");
                btndecline.setVisible(true);
            }
            case "Ambulance on the way" -> {
                btnaccept.setText("Ready for pickup");
                btndecline.setVisible(false);
            }
            default -> {
                btnaccept.setVisible(false);
                btndecline.setVisible(false);
            }
        }
        fillDelUI();
    }
}
