/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HospitalAdmin;

import EcoSystem.EcoSystem;
import EcoSystem.Hospital.HospitalAdmin;
import EcoSystem.LabAssistant.LabAssistant;
import EcoSystem.LabAssistant.LabAssistantDirectory;
import EcoSystem.Patient.Patient;
import EcoSystem.Patient.PatientDirectory;
import EcoSystem.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author shriyadikshith
 */
public class LabAssistantSchedule extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private HospitalAdmin hospitalAdmin;
    private DefaultTableModel defaultTableModel;
    private DefaultTableModel defaultCartTable;
    private int index = -1;
    private int row = 0;
    private int column = 0;
    private int quantity = 0;
    private EcoSystem ecosystem;
    private LabAssistantDirectory labAssistantDirectory;
    private PatientDirectory patientDirectory;
    /**
     * Creates new form LaAssistantSchedule
     */
    public LabAssistantSchedule(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        hospitalAdmin = (HospitalAdmin) account;
        labAssistantDirectory = ecosystem.getLabAssistantDirectory();
        patientDirectory = ecosystem.getPatientDirectory();
        
        fillRstList(labAssistantDirectory.getLabAssistantNameList());
        fillRstPatient(patientDirectory.getPatientList());
    }
    
    public void fillRstList(ArrayList<LabAssistant> labAssistantslist) {
        for (LabAssistant labAssistant : labAssistantslist) {
            comboLab.addItem(labAssistant.getLabAssistantName());
        }
    }
    
    public void fillRstPatient(ArrayList<Patient> patientList){
        for(Patient p : patientList){
            comboPatient.addItem(p.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        comboLab = new javax.swing.JComboBox<>();
        comboPatient = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(166, 203, 230));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Schedule");
        add(jLabel1);
        jLabel1.setBounds(300, 40, 182, 40);

        jButton1.setText("BACK");
        add(jButton1);
        jButton1.setBounds(40, 37, 108, 42);

        enterpriseLabel1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Choose Lab Assistant");
        add(enterpriseLabel1);
        enterpriseLabel1.setBounds(100, 140, 199, 21);

        enterpriseLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Choose Patient");
        add(enterpriseLabel2);
        enterpriseLabel2.setBounds(160, 180, 139, 21);

        jLabel2.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel2.setText("Enter Patient email");
        add(jLabel2);
        jLabel2.setBounds(120, 220, 177, 22);
        add(jTextField1);
        jTextField1.setBounds(370, 220, 146, 26);

        comboLab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboLab);
        comboLab.setBounds(370, 140, 146, 27);

        comboPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboPatient);
        comboPatient.setBounds(370, 180, 146, 27);

        jButton2.setText("BOOK AN APPOINTMENT");
        add(jButton2);
        jButton2.setBounds(560, 200, 234, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HospitalAdmin/labimg.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(30, 250, 760, 490);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboLab;
    private javax.swing.JComboBox<String> comboPatient;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
